# Generated by Django 5.2.4 on 2025-12-12 09:34

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="BankDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "account_name",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("bank_name", models.CharField(max_length=200)),
                ("bank_brnach_address", models.TextField()),
                ("bank_account_number", models.CharField(max_length=200)),
                ("bank_ifsc_code", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="CDRDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("job_name", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "cdr_corrections",
                    models.TextField(blank=True, max_length=900, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CylinderMadeIn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cylinder_made_in",
                    models.CharField(
                        blank=True, max_length=300, null=True, unique=True
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Job_detail",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date", models.DateField()),
                ("bill_no", models.CharField(max_length=200)),
                ("job_name", models.CharField(max_length=200)),
                (
                    "job_type",
                    models.CharField(
                        choices=[
                            ("New Job", "New Job"),
                            ("Damage Repair", "Damage Repair"),
                            ("Job Work", "Job Work"),
                        ],
                        max_length=200,
                    ),
                ),
                ("noc", models.TextField(blank=True, null=True)),
                ("prpc_purchase", models.CharField(max_length=200)),
                ("prpc_sell", models.CharField(blank=True, max_length=200, null=True)),
                ("cylinder_size", models.CharField(max_length=200)),
                ("cylinder_made_in", models.CharField(max_length=200)),
                ("pouch_size", models.CharField(max_length=200)),
                ("pouch_open_size", models.CharField(max_length=200)),
                (
                    "pouch_combination",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("correction", models.TextField(blank=True, null=True)),
                ("cylinder_date", models.DateField(blank=True, null=True)),
                ("cylinder_bill_no", models.CharField(blank=True, null=True)),
                (
                    "job_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("In Progress", "In Progress"),
                            ("Close Job", "Close Job"),
                        ],
                        max_length=200,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Party",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("party_name", models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Registration",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("first_name", models.CharField(blank=True, max_length=200, null=True)),
                ("last_name", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "email",
                    models.EmailField(
                        max_length=200,
                        unique=True,
                        validators=[django.core.validators.EmailValidator()],
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "abstract": False,
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="CDRImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="cdr_files/")),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "cdr",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cdr_images",
                        to="app.cdrdetail",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="JobHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("field_name", models.CharField(max_length=200)),
                ("old_value", models.TextField(blank=True, null=True)),
                ("new_value", models.TextField(blank=True, null=True)),
                ("changed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "chnage_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="job_history",
                        to="app.job_detail",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Jobimage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="job_images/")),
                ("upload_at", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="image",
                        to="app.job_detail",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="job_detail",
            name="party_details",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="app.party",
            ),
        ),
        migrations.AddField(
            model_name="cdrdetail",
            name="party_details",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cdr_party_details",
                to="app.party",
            ),
        ),
        migrations.CreateModel(
            name="PartyContact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("party_number", models.CharField(max_length=20)),
                (
                    "party",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="party_contacts",
                        to="app.party",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="cdrdetail",
            name="party_contact_used",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="app.partycontact",
            ),
        ),
        migrations.CreateModel(
            name="PartyEmail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=200)),
                (
                    "party",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="party_emails",
                        to="app.party",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="cdrdetail",
            name="party_email_used",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="app.partyemail",
            ),
        ),
        migrations.CreateModel(
            name="ProformaInvoice",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("invoice_no", models.CharField(max_length=200)),
                ("invoice_date", models.DateField()),
                ("mode_payment", models.CharField(default="100%", max_length=300)),
                ("billing_address", models.TextField()),
                ("billing_gstin_no", models.CharField(max_length=100)),
                (
                    "billing_state_name",
                    models.CharField(
                        choices=[
                            ("Andhra Pradesh", "Andhra Pradesh"),
                            ("Arunachal Pradesh", "Arunachal Pradesh"),
                            ("Assam", "Assam"),
                            ("Bihar", "Bihar"),
                            ("Chhattisgarh", "Chhattisgarh"),
                            ("Goa", "Goa"),
                            ("Gujarat", "Gujarat"),
                            ("Haryana", "Haryana"),
                            ("Himachal Pradesh", "Himachal Pradesh"),
                            ("Jharkhand", "Jharkhand"),
                            ("Karnataka", "Karnataka"),
                            ("Kerala", "Kerala"),
                            ("Madhya Pradesh", "Madhya Pradesh"),
                            ("Maharashtra", "Maharashtra"),
                            ("Manipur", "Manipur"),
                            ("Meghalaya", "Meghalaya"),
                            ("Mizoram", "Mizoram"),
                            ("Nagaland", "Nagaland"),
                            ("Odisha", "Odisha"),
                            ("Punjab", "Punjab"),
                            ("Rajasthan", "Rajasthan"),
                            ("Sikkim", "Sikkim"),
                            ("Tamil Nadu", "Tamil Nadu"),
                            ("Telangana", "Telangana"),
                            ("Tripura", "Tripura"),
                            ("Uttar Pradesh", "Uttar Pradesh"),
                            ("Uttarakhand", "Uttarakhand"),
                            ("West Bengal", "West Bengal"),
                        ],
                        max_length=200,
                    ),
                ),
                ("gst", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "total_taxable_value",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("gst_value", models.CharField(blank=True, max_length=200, null=True)),
                ("terms_note", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("total", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "invoice_status",
                    models.CharField(
                        blank=True,
                        choices=[("Pending", "Pending"), ("Confirmed", "Confirmed")],
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "bank_details",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bank_details",
                        to="app.bankdetails",
                    ),
                ),
                (
                    "party_contact_used",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="app.partycontact",
                    ),
                ),
                (
                    "party_details",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="party_details",
                        to="app.party",
                    ),
                ),
                (
                    "party_email_used",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="app.partyemail",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProformaJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("job_name", models.CharField(max_length=200)),
                ("quantity", models.CharField(max_length=200)),
                ("pouch_open_size", models.CharField(max_length=200)),
                ("cylinder_size", models.CharField(max_length=200)),
                ("prpc_rate", models.CharField(max_length=200)),
                (
                    "proforma_invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="job_details",
                        to="app.proformainvoice",
                    ),
                ),
            ],
        ),
    ]
