# Generated by Django 5.2.4 on 2025-12-15 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PouchQuotation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("delivery_date", models.DateField()),
                ("job_name", models.CharField(max_length=200)),
                ("pouch_open_size", models.CharField(max_length=200)),
                ("pouch_combination", models.CharField(max_length=200)),
                (
                    "purchase_rate_per_kg",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "no_of_pouch_kg",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "per_pouch_rate_basic",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("zipper_cost", models.DecimalField(decimal_places=2, max_digits=10)),
                ("final_rare", models.CharField(max_length=200)),
                ("minium_quantity", models.CharField(max_length=200)),
                (
                    "pouch_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("1 - Center Seal Pouch", "1 - Center Seal Pouch"),
                            ("2- 3 Side Seal Pouch", "2- 3 Side Seal Pouch"),
                            ("3- 6 Side Seal Pouch", "3- 6 Side Seal Pouch"),
                            (
                                "4- 6 Side Seal Pouch With D Cut",
                                "4- 6 Side Seal Pouch With D Cut",
                            ),
                            (
                                "5- Stand Up Pouch With Zipper",
                                "5- Stand Up Pouch With Zipper",
                            ),
                            ("6- Perforation Pouch", "6- Perforation Pouch"),
                            (
                                "7- 3 Side Seal Bag With Dori Handel",
                                "7- 3 Side Seal Bag With Dori Handel",
                            ),
                            (
                                "8- 3 Side Seal Zipper With V Nouch",
                                "8- 3 Side Seal Zipper With V Nouch",
                            ),
                            ("9- Printed Roll", "9- Printed Roll"),
                            (
                                "10- Flat Bottom Pouch With Zipper",
                                "10- Flat Bottom Pouch With Zipper",
                            ),
                        ],
                        max_length=200,
                        null=True,
                    ),
                ),
                ("special_instruction", models.TextField()),
                ("quantity", models.CharField(blank=True, max_length=200, null=True)),
                ("delivery_address", models.TextField()),
                ("quantity_variate", models.CharField(max_length=200)),
                ("freight", models.CharField(max_length=200)),
                ("gst", models.CharField(max_length=200)),
                ("note", models.TextField(max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "party_details",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="quotations_party_name",
                        to="app.party",
                    ),
                ),
            ],
        ),
    ]
