# Generated by Django 5.2.4 on 2025-11-12 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BankDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bank_name", models.CharField(max_length=200)),
                ("bank_brnach_address", models.TextField()),
                ("bank_account_number", models.CharField(max_length=200)),
                ("bank_ifsc_code", models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name="Demo",
        ),
        migrations.AddField(
            model_name="proformainvoice",
            name="bank_details",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="app.bankdetails",
            ),
        ),
    ]
