# Generated by Django 5.2.4 on 2025-11-12 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_bankdetails_delete_demo_proformainvoice_bank_details"),
    ]

    operations = [
        migrations.AlterField(
            model_name="proformainvoice",
            name="bank_details",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="bank_details",
                to="app.bankdetails",
            ),
        ),
    ]
