# Generated by Django 5.2.4 on 2025-12-16 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_pouchquotation"),
    ]

    operations = [
        migrations.AddField(
            model_name="pouchquotation",
            name="pouch_charge",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
