# Generated by Django 5.2.4 on 2025-11-12 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_alter_proformainvoice_bank_details"),
    ]

    operations = [
        migrations.AddField(
            model_name="bankdetails",
            name="account_name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
