# Generated by Django 5.2.4 on 2025-12-18 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_pouchquotation_pouch_charge"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pouchquotation",
            name="pouch_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Center Seal Pouch", "Center Seal Pouch"),
                    ("3 Side Seal Pouch", "3 Side Seal Pouch"),
                    ("6 Side Seal Pouch", "6 Side Seal Pouch"),
                    ("6 Side Seal Pouch With D Cut", "6 Side Seal Pouch With D Cut"),
                    ("Stand Up Pouch With Zipper", "Stand Up Pouch With Zipper"),
                    ("Perforation Pouch", "Perforation Pouch"),
                    (
                        "3 Side Seal Bag With Dori Handel",
                        "3 Side Seal Bag With Dori Handel",
                    ),
                    (
                        "3 Side Seal Zipper With V Nouch",
                        "3 Side Seal Zipper With V Nouch",
                    ),
                    ("Printed Roll", "Printed Roll"),
                    ("Flat Bottom Pouch With Zipper", "Flat Bottom Pouch With Zipper"),
                ],
                max_length=200,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="pouchquotation",
            name="purchase_rate_per_kg",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
