# Generated by Django 5.2.4 on 2025-07-22 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_companyname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('bill_no', models.CharField(max_length=200)),
                ('company_name', models.CharField(max_length=300)),
                ('job_name', models.CharField(max_length=200)),
                ('job_type', models.CharField(max_length=200)),
                ('noc', models.IntegerField(max_length=100)),
                ('prpc', models.CharField(max_length=200)),
                ('cylinder_size', models.CharField(max_length=200)),
                ('cylinder_made_in', models.CharField(max_length=200)),
                ('pouch_size', models.CharField(max_length=200)),
                ('pouch_open_size', models.CharField(max_length=200)),
                ('pouch_combination', models.CharField(max_length=200)),
                ('correction', models.TextField()),
                ('image_url', models.URLField()),
            ],
        ),
    ]
