# Generated by Django 5.2.4 on 2025-12-18 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_alter_pouchquotation_pouch_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pouchquotation",
            name="no_of_pouch_kg",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="pouchquotation",
            name="per_pouch_rate_basic",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="pouchquotation",
            name="zipper_cost",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
