# Generated by Django 5.2.4 on 2025-07-22 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_job_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job_detail',
            name='noc',
            field=models.IntegerField(),
        ),
    ]
