# Generated by Django 5.2.4 on 2025-12-19 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_alter_pouchquotation_no_of_pouch_kg_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PurchaseOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("delivery_date", models.DateField()),
                ("job_name", models.CharField(max_length=200)),
                ("pouch_open_size", models.CharField(max_length=200)),
                ("pouch_combination", models.CharField(max_length=200)),
                (
                    "purchase_rate_per_kg",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "polyester_unit",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("polyester_printed_roll", "Polyester Printed Roll"),
                            ("polyester_printed_bag", "Polyester Printed Bag"),
                        ],
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "no_of_pouch_kg",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "per_pouch_rate_basic",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "zipper_cost",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("final_rare", models.CharField(max_length=200)),
                ("minium_quantity", models.CharField(max_length=200)),
                (
                    "pouch_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Center Seal Pouch", "Center Seal Pouch"),
                            ("3 Side Seal Pouch", "3 Side Seal Pouch"),
                            ("6 Side Seal Pouch", "6 Side Seal Pouch"),
                            (
                                "6 Side Seal Pouch With D Cut",
                                "6 Side Seal Pouch With D Cut",
                            ),
                            (
                                "Stand Up Pouch With Zipper",
                                "Stand Up Pouch With Zipper",
                            ),
                            ("Perforation Pouch", "Perforation Pouch"),
                            (
                                "3 Side Seal Bag With Dori Handel",
                                "3 Side Seal Bag With Dori Handel",
                            ),
                            (
                                "3 Side Seal Zipper With V Nouch",
                                "3 Side Seal Zipper With V Nouch",
                            ),
                            ("Printed Roll", "Printed Roll"),
                            (
                                "Flat Bottom Pouch With Zipper",
                                "Flat Bottom Pouch With Zipper",
                            ),
                        ],
                        max_length=200,
                        null=True,
                    ),
                ),
                ("special_instruction", models.TextField()),
                ("quantity", models.CharField(blank=True, max_length=200, null=True)),
                ("delivery_address", models.TextField()),
                (
                    "pouch_charge",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("quantity_variate", models.CharField(max_length=200)),
                ("freight", models.CharField(max_length=200)),
                ("gst", models.CharField(max_length=200)),
                ("note", models.TextField(max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "party_details",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="purchase_party_name",
                        to="app.party",
                    ),
                ),
            ],
        ),
    ]
