# Generated by Django 5.2.4 on 2025-11-14 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_remove_company_company_email_companycontact_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="JobHeader",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("job_date", models.DateField()),
                ("bill_no", models.CharField(max_length=200)),
                (
                    "company_name",
                    models.CharField(blank=True, max_length=300, null=True),
                ),
                ("correction", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "job_status",
                    models.CharField(
                        choices=[("Pending", "Pending"), ("Confirmed", "Confirmed")],
                        max_length=200,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="JobMaterial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("job_name", models.CharField(max_length=200)),
                ("job_type", models.CharField(max_length=200)),
                ("noc", models.CharField(max_length=200)),
                ("prpc_purchase", models.CharField(max_length=200)),
                ("prpc_sell", models.CharField(blank=True, max_length=200, null=True)),
                ("cylinder_size", models.CharField(max_length=200)),
                ("cylinder_made_in", models.CharField(max_length=200)),
                ("pouch_size", models.CharField(max_length=200)),
                ("pouch_open_size", models.CharField(max_length=200)),
                ("pouch_combination", models.CharField(max_length=200)),
                ("cylinder_date", models.DateField(blank=True, null=True)),
                ("cylinder_bill_no", models.CharField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="job_materials",
                        to="app.jobheader",
                    ),
                ),
            ],
        ),
    ]
