# Generated by Django 5.2.4 on 2025-07-24 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_job_detail_noc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job_detail',
            old_name='image_url',
            new_name='folder_url',
        ),
        migrations.AddField(
            model_name='job_detail',
            name='image_links',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
