# Generated by Django 5.2.4 on 2025-12-22 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0006_purchaseorder"),
    ]

    operations = [
        migrations.RenameField(
            model_name="pouchquotation",
            old_name="minium_quantity",
            new_name="minimum_quantity",
        ),
        migrations.RenameField(
            model_name="purchaseorder",
            old_name="minium_quantity",
            new_name="minimum_quantity",
        ),
    ]
