# Generated by Django 5.2.4 on 2025-11-14 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0006_jobheader_jobmaterial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job_detail",
            name="job_status",
            field=models.CharField(
                blank=True,
                choices=[("Pending", "Pending"), ("Confirmed", "Confirmed")],
                max_length=200,
                null=True,
            ),
        ),
    ]
