# Generated by Django 5.2.4 on 2025-07-29 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rename_image_url_job_detail_folder_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CylinderMadeIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cylinder_made_in', models.CharField(max_length=300)),
            ],
        ),
    ]
