# Generated by Django 5.2.4 on 2025-12-23 07:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0007_rename_minium_quantity_pouchquotation_minimum_quantity_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PartyBillingAddress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("billing_address", models.TextField(blank=True, null=True)),
                (
                    "party",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="party_billing_addresses",
                        to="app.party",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="proformainvoice",
            name="party_billing_address_used",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="app.partybillingaddress",
            ),
        ),
    ]
