# Generated by Django 5.2.4 on 2025-07-29 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_cylindermadein'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyname',
            name='company_name',
            field=models.CharField(max_length=300, unique=True),
        ),
        migrations.AlterField(
            model_name='cylindermadein',
            name='cylinder_made_in',
            field=models.CharField(max_length=300, unique=True),
        ),
    ]
