# Generated by Django 5.2.4 on 2025-11-14 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0007_alter_job_detail_job_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job_detail",
            name="job_status",
            field=models.CharField(
                blank=True,
                choices=[("In Progress", "In Progress"), ("Close Job", "Close Job")],
                max_length=200,
                null=True,
            ),
        ),
    ]
