# Generated by Django 5.2.4 on 2025-07-29 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_companyname_company_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cylindermadein',
            name='cylinder_made_in',
            field=models.CharField(blank=True, max_length=300, null=True, unique=True),
        ),
    ]
