# Generated by Django 5.2.4 on 2025-12-23 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0008_partybillingaddress_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="proformainvoice",
            name="billing_address",
        ),
    ]
