# Generated by Django 5.2.4 on 2025-11-17 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0008_alter_job_detail_job_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="jobmaterial",
            name="job",
        ),
        migrations.DeleteModel(
            name="JobHeader",
        ),
        migrations.DeleteModel(
            name="JobMaterial",
        ),
    ]
