# Generated by Django 5.2.4 on 2025-12-29 06:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0009_remove_proformainvoice_billing_address"),
    ]

    operations = [
        migrations.CreateModel(
            name="PouchQuotationJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("job_name", models.CharField(max_length=200)),
                ("quantity", models.CharField(max_length=200)),
                ("purchase_rate_per_kg", models.CharField(max_length=200)),
                ("no_of_pouch_kg", models.CharField(max_length=200)),
                ("pouch_open_size", models.CharField(max_length=200)),
                ("delivery_address", models.TextField()),
                ("minimum_quantity", models.CharField(max_length=200)),
                ("final_rare", models.CharField(max_length=200)),
                ("per_pouch_rate_basic", models.CharField(max_length=200)),
                ("zipper_cost", models.CharField(max_length=200)),
                ("pouch_combination", models.CharField(max_length=200)),
                ("pouch_type", models.CharField(max_length=200)),
                ("special_instruction", models.TextField()),
                ("pouch_charge", models.CharField(max_length=200)),
                (
                    "quotation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pouch_quotation_jobs",
                        to="app.pouchquotation",
                    ),
                ),
            ],
        ),
    ]
