# Generated by Django 5.2.4 on 2025-11-20 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0009_remove_jobmaterial_job_delete_jobheader_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job_detail",
            name="pouch_combination",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
