# Generated by Django 5.2.4 on 2025-08-01 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_cylindermadein_cylinder_made_in'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job_detail',
            old_name='prpc',
            new_name='prpc_purchase',
        ),
        migrations.AddField(
            model_name='job_detail',
            name='prpc_sell',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
