# Generated by Django 5.2.4 on 2025-11-24 07:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0010_alter_job_detail_pouch_combination"),
    ]

    operations = [
        migrations.AddField(
            model_name="proformainvoice",
            name="company_details",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="company_details",
                to="app.company",
            ),
        ),
    ]
