# Generated by Django 5.2.4 on 2025-08-06 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_rename_prpc_job_detail_prpc_purchase_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job_detail',
            name='correction',
            field=models.TextField(blank=True, null=True),
        ),
    ]
