# Generated by Django 5.2.4 on 2025-12-29 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0010_pouchquotationjob"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pouchquotation",
            name="job_name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="pouchquotation",
            name="pouch_combination",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="pouchquotation",
            name="pouch_open_size",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
