# Generated by Django 5.2.4 on 2025-11-24 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0011_proformainvoice_company_details"),
    ]

    operations = [
        migrations.AlterField(
            model_name="companycontact",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="company_contacts",
                to="app.company",
            ),
        ),
        migrations.AlterField(
            model_name="companyemail",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="company_emails",
                to="app.company",
            ),
        ),
    ]
