# Generated by Django 5.2.4 on 2025-12-30 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0011_alter_pouchquotation_job_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pouchquotation",
            name="delivery_address",
        ),
        migrations.RemoveField(
            model_name="pouchquotation",
            name="final_rare",
        ),
        migrations.RemoveField(
            model_name="pouchquotation",
            name="job_name",
        ),
        migrations.RemoveField(
            model_name="pouchquotation",
            name="minimum_quantity",
        ),
        migrations.RemoveField(
            model_name="pouchquotation",
            name="no_of_pouch_kg",
        ),
        migrations.RemoveField(
            model_name="pouchquotation",
            name="per_pouch_rate_basic",
        ),
        migrations.RemoveField(
            model_name="pouchquotation",
            name="pouch_charge",
        ),
        migrations.RemoveField(
            model_name="pouchquotation",
            name="pouch_combination",
        ),
        migrations.RemoveField(
            model_name="pouchquotation",
            name="pouch_open_size",
        ),
        migrations.RemoveField(
            model_name="pouchquotation",
            name="pouch_type",
        ),
        migrations.RemoveField(
            model_name="pouchquotation",
            name="purchase_rate_per_kg",
        ),
        migrations.RemoveField(
            model_name="pouchquotation",
            name="quantity",
        ),
        migrations.RemoveField(
            model_name="pouchquotation",
            name="special_instruction",
        ),
        migrations.RemoveField(
            model_name="pouchquotation",
            name="zipper_cost",
        ),
    ]
