# Generated by Django 5.2.4 on 2025-08-07 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_job_detail_correction'),
    ]

    operations = [
        migrations.AddField(
            model_name='job_detail',
            name='cylinder_bill_no',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job_detail',
            name='cylinder_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
