# Generated by Django 5.2.4 on 2025-08-07 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_job_detail_cylinder_bill_no_job_detail_cylinder_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job_detail',
            name='noc',
            field=models.TextField(blank=True, null=True),
        ),
    ]
