# Generated by Django 5.2.4 on 2025-11-24 11:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0012_alter_companycontact_company_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Party",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("party_name", models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="companycontact",
            name="company",
        ),
        migrations.RemoveField(
            model_name="proformainvoice",
            name="company_details",
        ),
        migrations.AddField(
            model_name="proformainvoice",
            name="party_details",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="party_details",
                to="app.party",
            ),
        ),
        migrations.CreateModel(
            name="PartyContact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("party_number", models.CharField(max_length=20)),
                (
                    "party",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="party_contacts",
                        to="app.party",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PartyEmail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=200)),
                (
                    "party",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="party_emails",
                        to="app.party",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="CompanyEmail",
        ),
        migrations.DeleteModel(
            name="CompanyContact",
        ),
        migrations.DeleteModel(
            name="Company",
        ),
    ]
