# Generated by Django 5.2.4 on 2025-11-25 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0013_party_remove_companycontact_company_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="proformainvoice",
            name="company_contact",
        ),
        migrations.RemoveField(
            model_name="proformainvoice",
            name="company_email",
        ),
        migrations.RemoveField(
            model_name="proformainvoice",
            name="company_name",
        ),
    ]
