# Generated by Django 5.2.4 on 2025-08-11 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_job_detail_noc'),
    ]

    operations = [
        migrations.CreateModel(
            name='CDRDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('company_name', models.CharField(max_length=200)),
                ('company_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('file_url', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
