# Generated by Django 5.2.4 on 2025-11-25 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0014_remove_proformainvoice_company_contact_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="proformainvoice",
            name="company_contact",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="proformainvoice",
            name="company_email",
            field=models.EmailField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="proformainvoice",
            name="company_name",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
