# Generated by Django 5.2.4 on 2025-08-11 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_cdrdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='cdrdetail',
            name='cdr_upload',
            field=models.FileField(blank=True, null=True, upload_to='cdr_file/'),
        ),
    ]
