# Generated by Django 5.2.4 on 2025-12-31 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0014_alter_pouchquotationjob_pouch_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="purchaseorder",
            name="delivery_address",
        ),
        migrations.RemoveField(
            model_name="purchaseorder",
            name="final_rare",
        ),
        migrations.RemoveField(
            model_name="purchaseorder",
            name="job_name",
        ),
        migrations.RemoveField(
            model_name="purchaseorder",
            name="minimum_quantity",
        ),
        migrations.RemoveField(
            model_name="purchaseorder",
            name="no_of_pouch_kg",
        ),
        migrations.RemoveField(
            model_name="purchaseorder",
            name="per_pouch_rate_basic",
        ),
        migrations.RemoveField(
            model_name="purchaseorder",
            name="polyester_unit",
        ),
        migrations.RemoveField(
            model_name="purchaseorder",
            name="pouch_charge",
        ),
        migrations.RemoveField(
            model_name="purchaseorder",
            name="pouch_combination",
        ),
        migrations.RemoveField(
            model_name="purchaseorder",
            name="pouch_open_size",
        ),
        migrations.RemoveField(
            model_name="purchaseorder",
            name="pouch_type",
        ),
        migrations.RemoveField(
            model_name="purchaseorder",
            name="purchase_rate_per_kg",
        ),
        migrations.RemoveField(
            model_name="purchaseorder",
            name="quantity",
        ),
        migrations.RemoveField(
            model_name="purchaseorder",
            name="special_instruction",
        ),
        migrations.RemoveField(
            model_name="purchaseorder",
            name="zipper_cost",
        ),
        migrations.AddField(
            model_name="purchaseorderjob",
            name="polyester_unit",
            field=models.CharField(
                blank=True,
                choices=[
                    ("polyester_printed_roll", "Polyester Printed Roll"),
                    ("polyester_printed_bag", "Polyester Printed Bag"),
                ],
                max_length=200,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="purchaseorderjob",
            name="pouch_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Center Seal Pouch", "Center Seal Pouch"),
                    ("3 Side Seal Pouch", "3 Side Seal Pouch"),
                    ("6 Side Seal Pouch", "6 Side Seal Pouch"),
                    ("6 Side Seal Pouch With D Cut", "6 Side Seal Pouch With D Cut"),
                    ("Stand Up Pouch With Zipper", "Stand Up Pouch With Zipper"),
                    ("Perforation Pouch", "Perforation Pouch"),
                    (
                        "3 Side Seal Bag With Dori Handel",
                        "3 Side Seal Bag With Dori Handel",
                    ),
                    (
                        "3 Side Seal Zipper With V Nouch",
                        "3 Side Seal Zipper With V Nouch",
                    ),
                    ("Printed Roll", "Printed Roll"),
                    ("Flat Bottom Pouch With Zipper", "Flat Bottom Pouch With Zipper"),
                ],
                max_length=200,
                null=True,
            ),
        ),
    ]
