# Generated by Django 5.2.4 on 2025-08-11 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_cdrdetail_cdr_upload'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cdrdetail',
            name='cdr_upload',
        ),
    ]
