# Generated by Django 5.2.4 on 2026-01-02 11:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0015_remove_purchaseorder_delivery_address_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PouchParty",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("party_name", models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name="pouchquotation",
            name="party_details",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="quotations_party_name",
                to="app.pouchparty",
            ),
        ),
        migrations.AlterField(
            model_name="purchaseorder",
            name="party_details",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="purchase_party_name",
                to="app.pouchparty",
            ),
        ),
        migrations.CreateModel(
            name="PouchPartyContact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("party_number", models.CharField(max_length=20)),
                (
                    "party",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pouch_party_contacts",
                        to="app.pouchparty",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PouchPartyEmail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=200)),
                (
                    "party",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pouch_party_emails",
                        to="app.pouchparty",
                    ),
                ),
            ],
        ),
    ]
