# Generated by Django 5.2.4 on 2025-11-25 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0016_proformainvoice_party_contact_used_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="proformainvoice",
            name="company_contact",
        ),
        migrations.RemoveField(
            model_name="proformainvoice",
            name="company_email",
        ),
        migrations.RemoveField(
            model_name="proformainvoice",
            name="company_name",
        ),
    ]
