# Generated by Django 5.2.4 on 2026-01-16 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0016_pouchparty_alter_pouchquotation_party_details_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="pouchquotation",
            name="pouch_quotation_number",
            field=models.CharField(default="234KG@$S", max_length=200),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="pouch_purchase_number",
            field=models.CharField(default="234KG@$S", max_length=200),
        ),
    ]
