# Generated by Django 5.2.4 on 2025-08-12 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_remove_cdrdetail_cdr_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='cdrdetail',
            name='image_link',
            field=models.URLField(blank=True, max_length=700, null=True),
        ),
        migrations.AlterField(
            model_name='cdrdetail',
            name='company_email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
