# Generated by Django 5.2.4 on 2026-01-16 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0017_pouchquotation_pouch_quotation_number_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pouchquotation",
            name="pouch_quotation_number",
            field=models.CharField(
                blank=True, default="234KG@$S", max_length=200, null=True
            ),
        ),
        migrations.AlterField(
            model_name="purchaseorder",
            name="pouch_purchase_number",
            field=models.CharField(
                blank=True, default="234KG@$S", max_length=200, null=True
            ),
        ),
    ]
