# Generated by Django 5.2.4 on 2025-11-25 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0017_remove_proformainvoice_company_contact_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="proformainvoice",
            name="party_contact_used",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="app.partycontact",
            ),
        ),
        migrations.AlterField(
            model_name="proformainvoice",
            name="party_email_used",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="app.partyemail",
            ),
        ),
    ]
