# Generated by Django 5.2.4 on 2025-08-12 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_cdrdetail_image_link_alter_cdrdetail_company_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cdrdetail',
            name='image_link',
        ),
        migrations.AddField(
            model_name='cdrdetail',
            name='image_url',
            field=models.URLField(blank=True, max_length=900, null=True),
        ),
        migrations.AddField(
            model_name='cdrdetail',
            name='job_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
