# Generated by Django 5.2.4 on 2026-01-16 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0018_alter_pouchquotation_pouch_quotation_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="pouchquotation",
            name="party_email",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pouch_quotation_party_email",
                to="app.pouchpartyemail",
            ),
        ),
    ]
