# Generated by Django 5.2.4 on 2025-08-13 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_remove_cdrdetail_image_link_cdrdetail_image_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cdrdetail',
            name='company_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
