# Generated by Django 5.2.4 on 2025-11-25 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0018_alter_proformainvoice_party_contact_used_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cdrdetail",
            name="company_email",
        ),
        migrations.RemoveField(
            model_name="cdrdetail",
            name="company_name",
        ),
        migrations.AddField(
            model_name="cdrdetail",
            name="party_contact_used",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="app.partycontact",
            ),
        ),
        migrations.AddField(
            model_name="cdrdetail",
            name="party_details",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cdr_party_details",
                to="app.party",
            ),
        ),
        migrations.AddField(
            model_name="cdrdetail",
            name="party_email_used",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="app.partyemail",
            ),
        ),
    ]
