# Generated by Django 5.2.4 on 2025-08-13 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_alter_cdrdetail_company_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='cdrdetail',
            name='cdr_corrections',
            field=models.TextField(blank=True, max_length=900, null=True),
        ),
    ]
