# Generated by Django 5.2.4 on 2026-01-16 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0019_pouchquotation_party_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchaseorder",
            name="party_email",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pouch_purchase_party_email",
                to="app.pouchpartyemail",
            ),
        ),
    ]
