# Generated by Django 5.2.4 on 2025-12-02 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0019_remove_cdrdetail_company_email_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cdrdetail",
            name="file_url",
        ),
        migrations.RemoveField(
            model_name="cdrdetail",
            name="image_url",
        ),
    ]
