# Generated by Django 5.2.4 on 2026-01-19 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0020_purchaseorder_party_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="pouchquotationjob",
            name="polyester_unit",
            field=models.CharField(
                blank=True,
                choices=[
                    ("polyester_printed_roll", "Polyester Printed Roll"),
                    ("polyester_printed_bag", "Polyester Printed Bag"),
                ],
                max_length=200,
                null=True,
            ),
        ),
    ]
