# Generated by Django 5.2.4 on 2025-08-21 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_cdrdetail_cdr_corrections'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyname',
            name='company_name',
            field=models.CharField(max_length=300),
        ),
    ]
