# Generated by Django 5.2.4 on 2025-12-04 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0020_remove_cdrdetail_file_url_remove_cdrdetail_image_url"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CompanyName",
        ),
    ]
