# Generated by Django 5.2.4 on 2025-12-04 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0021_delete_companyname"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="job_detail",
            name="folder_url",
        ),
        migrations.RemoveField(
            model_name="job_detail",
            name="image_links",
        ),
        migrations.AlterField(
            model_name="job_detail",
            name="job_type",
            field=models.CharField(
                choices=[
                    ("New Job", "New Job"),
                    ("Damage Repair", "Damage Repair"),
                    ("Job Work", "Job Work"),
                ],
                max_length=200,
            ),
        ),
    ]
