# Generated by Django 5.2.4 on 2026-01-21 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0021_pouchquotationjob_polyester_unit"),
    ]

    operations = [
        migrations.RenameField(
            model_name="pouchquotationjob",
            old_name="final_rare",
            new_name="final_rate",
        ),
        migrations.RenameField(
            model_name="purchaseorderjob",
            old_name="final_rare",
            new_name="final_rate",
        ),
    ]
