# Generated by Django 5.2.4 on 2025-08-28 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_alter_companyname_company_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='job_detail',
            name='job_status',
            field=models.CharField(default='In Progress', max_length=200),
        ),
    ]
