# Generated by Django 5.2.4 on 2025-12-04 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0022_remove_job_detail_folder_url_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="job_detail",
            name="party_details",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="app.party",
            ),
        ),
    ]
