# Generated by Django 5.2.4 on 2026-01-23 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0022_rename_final_rare_pouchquotationjob_final_rate_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pouchquotationjob",
            name="final_rate",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name="pouchquotationjob",
            name="no_of_pouch_kg",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="pouchquotationjob",
            name="per_pouch_rate_basic",
            field=models.DecimalField(decimal_places=4, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name="pouchquotationjob",
            name="pouch_charge",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="pouchquotationjob",
            name="purchase_rate_per_kg",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="pouchquotationjob",
            name="quantity",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="pouchquotationjob",
            name="zipper_cost",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
