# Generated by Django 5.2.4 on 2025-08-28 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_job_detail_job_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job_detail',
            name='job_status',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
