# Generated by Django 5.2.4 on 2025-08-29 07:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_alter_job_detail_job_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jobimage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='job_images/')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.job_detail')),
            ],
        ),
    ]
