# Generated by Django 5.2.4 on 2025-12-04 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0023_job_detail_party_details"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="job_detail",
            name="company_name",
        ),
    ]
