# Generated by Django 5.2.4 on 2025-08-29 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_jobimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='CDRImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='cdr_files/')),
                ('cdr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.cdrdetail')),
            ],
        ),
    ]
