# Generated by Django 5.2.4 on 2026-01-23 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0024_alter_pouchquotationjob_final_rate_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pouchquotationjob",
            name="minimum_quantity",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=10, null=True
            ),
        ),
    ]
