# Generated by Django 5.2.4 on 2025-09-02 06:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_cdrimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobimage',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='app.job_detail'),
        ),
    ]
