# Generated by Django 5.2.4 on 2026-01-27 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0026_alter_cdrdetail_job_name_alter_job_detail_bill_no_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="pouchquotation",
            name="pouch_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Pending", "Pending"),
                    ("Approved", "Approved"),
                    ("Cancelled", "Cancelled"),
                ],
                default="Pending",
                max_length=200,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="pouch_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Pending", "Pending"),
                    ("Approved", "Approved"),
                    ("Cancelled", "Cancelled"),
                ],
                default="Pending",
                max_length=200,
                null=True,
            ),
        ),
    ]
