# Generated by Django 5.2.4 on 2026-01-27 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0027_pouchquotation_pouch_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pouchquotation",
            name="pouch_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Pending", "Pending"),
                    ("Approved", "Approved"),
                    ("Rejected", "Rejected"),
                    ("Cancelled", "Cancelled"),
                    ("Delivered", "Delivered"),
                ],
                max_length=200,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="purchaseorder",
            name="pouch_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Pending", "Pending"),
                    ("Approved", "Approved"),
                    ("Rejected", "Rejected"),
                    ("Cancelled", "Cancelled"),
                    ("Delivered", "Delivered"),
                ],
                max_length=200,
                null=True,
            ),
        ),
    ]
