# Generated by Django 5.2.4 on 2025-09-02 07:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_alter_jobimage_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cdrimage',
            name='cdr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cdr_images', to='app.cdrdetail'),
        ),
    ]
