# Generated by Django 5.2.4 on 2026-01-27 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0028_alter_pouchquotation_pouch_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchaseorderjob",
            name="final_rate",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=12, null=True
            ),
        ),
        migrations.AlterField(
            model_name="purchaseorderjob",
            name="minimum_quantity",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="purchaseorderjob",
            name="no_of_pouch_kg",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="purchaseorderjob",
            name="per_pouch_rate_basic",
            field=models.DecimalField(
                blank=True, decimal_places=4, default=0, max_digits=12, null=True
            ),
        ),
        migrations.AlterField(
            model_name="purchaseorderjob",
            name="pouch_charge",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="purchaseorderjob",
            name="purchase_rate_per_kg",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="purchaseorderjob",
            name="quantity",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="purchaseorderjob",
            name="zipper_cost",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=10, null=True
            ),
        ),
    ]
