# Generated by Django 5.2.4 on 2026-01-28 10:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0029_alter_purchaseorderjob_final_rate_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="pouchquotation",
            name="party_contact",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pouch_quotation_party_contact",
                to="app.pouchpartycontact",
            ),
        ),
        migrations.CreateModel(
            name="PouchDeliveryAddress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("delivery_address", models.CharField(max_length=200)),
                (
                    "party",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pouch_party_delivery_addresses",
                        to="app.pouchparty",
                    ),
                ),
            ],
        ),
    ]
