# Generated by Django 5.2.4 on 2025-09-05 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_cdrdetail_cdr_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cdrdetail',
            name='cdr_url',
        ),
    ]
