# Generated by Django 5.2.4 on 2026-01-29 05:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0030_pouchquotation_party_contact_pouchdeliveryaddress"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchaseorder",
            name="party_contact",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pouch_purchase_party_contact",
                to="app.pouchpartycontact",
            ),
        ),
    ]
