# Generated by Django 5.2.4 on 2025-09-05 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_remove_cdrdetail_cdr_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='cdrdetail',
            name='cdr_url',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='urls', to='app.job_detail'),
        ),
    ]
