# Generated by Django 5.2.4 on 2026-02-02 05:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0031_purchaseorder_party_contact"),
    ]

    operations = [
        migrations.CreateModel(
            name="PouchMaster",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("job_name", models.CharField(blank=True, max_length=500, null=True)),
                ("pouch_open_size", models.CharField(max_length=200)),
                ("pouch_combination", models.CharField(max_length=200)),
                ("purchase_rate_per_kg", models.CharField(max_length=200)),
                (
                    "minimum_quantity",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "no_of_pouch_per_kg",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "party_contact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pouch_master_party_contact",
                        to="app.pouchpartycontact",
                    ),
                ),
                (
                    "party_details",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pouch_master_party_details",
                        to="app.pouchparty",
                    ),
                ),
                (
                    "party_email",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pouch_master_party_email",
                        to="app.pouchpartyemail",
                    ),
                ),
            ],
        ),
    ]
