# Generated by Django 5.2.4 on 2026-02-09 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0032_pouchmaster"),
    ]

    operations = [
        migrations.RenameField(
            model_name="pouchquotationjob",
            old_name="per_pouch_rate_basic",
            new_name="rate_basic",
        ),
        migrations.AlterField(
            model_name="pouchquotationjob",
            name="job_name",
            field=models.CharField(db_index=True, max_length=200),
        ),
    ]
