# Generated by Django 5.2.4 on 2026-01-30 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0032_pouchmaster"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pouchmaster",
            name="minimum_quantity",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="pouchmaster",
            name="no_of_pouch_per_kg",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
