# Generated by Django 5.2.4 on 2025-09-09 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_remove_cdrdetail_cdr_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='job_detail',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
