# Generated by Django 5.2.4 on 2026-02-09 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "app",
            "0033_rename_per_pouch_rate_basic_pouchquotationjob_rate_basic_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="pouchquotationjob",
            name="rate_basic",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=12, null=True
            ),
        ),
    ]
