# Generated by Django 5.2.4 on 2026-02-09 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0034_alter_pouchquotationjob_rate_basic"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="purchaseorderjob",
            name="per_pouch_rate_basic",
        ),
        migrations.AddField(
            model_name="purchaseorderjob",
            name="rate_basic",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=12, null=True
            ),
        ),
    ]
