# Generated by Django 5.2.4 on 2025-09-30 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_alter_registration_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job_detail',
            name='company_name',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
