# Generated by Django 5.2.4 on 2025-09-30 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_alter_job_detail_company_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyname',
            name='company_name',
            field=models.CharField(max_length=300, unique=True),
        ),
    ]
