# Generated by Django 5.2.4 on 2026-02-10 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0035_remove_purchaseorderjob_per_pouch_rate_basic_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pouchmaster",
            name="party_details",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="pouch_master_party_details",
                to="app.pouchparty",
            ),
        ),
    ]
