# Generated by Django 5.2.4 on 2026-02-10 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0036_alter_pouchmaster_party_details"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pouchmaster",
            name="party_contact",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="pouch_master_party_contact",
                to="app.pouchpartycontact",
            ),
        ),
        migrations.AlterField(
            model_name="pouchmaster",
            name="party_email",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="pouch_master_party_email",
                to="app.pouchpartyemail",
            ),
        ),
    ]
