# Generated by Django 5.2.4 on 2025-09-30 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_alter_companyname_company_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyname',
            name='company_name',
            field=models.CharField(max_length=300),
        ),
    ]
