# Generated by Django 5.2.4 on 2025-10-06 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_alter_companyname_company_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobimage',
            name='upload_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
