# Generated by Django 5.2.4 on 2026-02-11 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0037_alter_pouchmaster_party_contact_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pouchquotationjob",
            name="minimum_quantity",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=20, null=True
            ),
        ),
        migrations.AlterField(
            model_name="purchaseorderjob",
            name="minimum_quantity",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=20, null=True
            ),
        ),
    ]
