# Generated by Django 5.2.4 on 2025-10-07 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_jobimage_upload_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='cdrimage',
            name='thumbnail_image',
            field=models.ImageField(blank=True, null=True, upload_to='cdr_thumbnail_image/'),
        ),
    ]
