# Generated by Django 5.2.4 on 2026-02-11 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0038_alter_pouchquotationjob_minimum_quantity_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pouchquotationjob",
            name="final_rate",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=20, null=True
            ),
        ),
        migrations.AlterField(
            model_name="pouchquotationjob",
            name="no_of_pouch_kg",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=20, null=True
            ),
        ),
        migrations.AlterField(
            model_name="pouchquotationjob",
            name="pouch_charge",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=20, null=True
            ),
        ),
        migrations.AlterField(
            model_name="pouchquotationjob",
            name="purchase_rate_per_kg",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=20, null=True
            ),
        ),
        migrations.AlterField(
            model_name="pouchquotationjob",
            name="quantity",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=20, null=True
            ),
        ),
        migrations.AlterField(
            model_name="pouchquotationjob",
            name="rate_basic",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=20, null=True
            ),
        ),
        migrations.AlterField(
            model_name="pouchquotationjob",
            name="zipper_cost",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=20, null=True
            ),
        ),
        migrations.AlterField(
            model_name="purchaseorderjob",
            name="final_rate",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=20, null=True
            ),
        ),
        migrations.AlterField(
            model_name="purchaseorderjob",
            name="no_of_pouch_kg",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=20, null=True
            ),
        ),
        migrations.AlterField(
            model_name="purchaseorderjob",
            name="pouch_charge",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=20, null=True
            ),
        ),
        migrations.AlterField(
            model_name="purchaseorderjob",
            name="purchase_rate_per_kg",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=20, null=True
            ),
        ),
        migrations.AlterField(
            model_name="purchaseorderjob",
            name="quantity",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=20, null=True
            ),
        ),
        migrations.AlterField(
            model_name="purchaseorderjob",
            name="rate_basic",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=20, null=True
            ),
        ),
        migrations.AlterField(
            model_name="purchaseorderjob",
            name="zipper_cost",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=20, null=True
            ),
        ),
    ]
