# Generated by Django 5.2.4 on 2026-02-20 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0039_alter_pouchquotationjob_final_rate_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pouchmaster",
            name="purchase_rate_per_kg",
            field=models.CharField(default=0.0, max_length=200),
        ),
    ]
