# Generated by Django 5.2.4 on 2025-10-07 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0039_cdrimage_thumbnail_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cdrimage',
            name='thumbnail_image',
            field=models.FileField(blank=True, null=True, upload_to='cdr_thumbnail_image/'),
        ),
    ]
