# Generated by Django 5.2.4 on 2025-10-09 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0040_alter_cdrimage_thumbnail_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='cdrimage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
