# Generated by Django 5.2.4 on 2026-02-25 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0040_alter_pouchmaster_purchase_rate_per_kg"),
    ]

    operations = [
        migrations.AddField(
            model_name="pouchmaster",
            name="sr_no",
            field=models.CharField(
                auto_created=True, blank=True, max_length=200, null=True, unique=True
            ),
        ),
    ]
