# Generated by Django 5.2.4 on 2025-10-27 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0041_cdrimage_created_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cdrimage",
            name="thumbnail_image",
        ),
    ]
