# Generated by Django 5.2.4 on 2026-02-25 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0041_pouchmaster_sr_no"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pouchmaster",
            name="sr_no",
            field=models.IntegerField(
                auto_created=True, blank=True, null=True, unique=True
            ),
        ),
    ]
