# Generated by Django 5.2.4 on 2025-10-28 06:25

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0042_remove_cdrimage_thumbnail_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalJob_detail",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("date", models.DateField()),
                ("bill_no", models.CharField(max_length=200)),
                (
                    "company_name",
                    models.CharField(blank=True, max_length=300, null=True),
                ),
                ("job_name", models.CharField(max_length=200)),
                ("job_type", models.CharField(max_length=200)),
                ("noc", models.TextField(blank=True, null=True)),
                ("prpc_purchase", models.CharField(max_length=200)),
                ("prpc_sell", models.CharField(blank=True, max_length=200, null=True)),
                ("cylinder_size", models.CharField(max_length=200)),
                ("cylinder_made_in", models.CharField(max_length=200)),
                ("pouch_size", models.CharField(max_length=200)),
                ("pouch_open_size", models.CharField(max_length=200)),
                ("pouch_combination", models.CharField(max_length=200)),
                ("correction", models.TextField(blank=True, null=True)),
                ("folder_url", models.URLField()),
                (
                    "image_links",
                    models.CharField(blank=True, max_length=1000, null=True),
                ),
                ("cylinder_date", models.DateField(blank=True, null=True)),
                ("cylinder_bill_no", models.CharField(blank=True, null=True)),
                ("job_status", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "created_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical job_detail",
                "verbose_name_plural": "historical job_details",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
