# Generated by Django 5.2.4 on 2026-02-27 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0042_alter_pouchmaster_sr_no"),
    ]

    operations = [
        migrations.CreateModel(
            name="PartyBillingGSTIN",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "billing_gstin",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "party",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="party_billing_gstin",
                        to="app.party",
                    ),
                ),
            ],
        ),
    ]
