# Generated by Django 5.2.4 on 2026-02-27 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0043_partybillinggstin"),
    ]

    operations = [
        migrations.AlterField(
            model_name="proformainvoice",
            name="billing_gstin_no",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="app.partybillinggstin",
            ),
        ),
    ]
