# Generated by Django 5.2.4 on 2025-10-29 09:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0044_jobhistory_delete_historicaljob_detail"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProformaInvoice",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("invoice_no", models.CharField(max_length=200, unique=True)),
                ("invoice_date", models.DateField()),
                ("mode_payment", models.CharField(max_length=300)),
                ("company_name", models.CharField(max_length=300)),
                ("company_contact", models.CharField(max_length=200)),
                ("company_email", models.EmailField(max_length=200)),
                ("billing_address", models.TextField()),
                ("billing_gstin_no", models.CharField(max_length=100)),
                ("billing_state_name", models.CharField(max_length=200)),
                ("title", models.CharField(max_length=200)),
                ("job_name", models.CharField(max_length=200)),
                ("quantity", models.IntegerField()),
                ("pouch_open_size", models.CharField(max_length=200)),
                ("cylinder_size", models.CharField(max_length=200)),
                ("prpc_rate", models.DecimalField(decimal_places=2, max_digits=10)),
                ("banking_details", models.TextField()),
                ("total", models.DecimalField(decimal_places=2, max_digits=15)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
