# Generated by Django 5.2.4 on 2025-10-29 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0045_proformainvoice"),
    ]

    operations = [
        migrations.AlterField(
            model_name="proformainvoice",
            name="mode_payment",
            field=models.CharField(default="100%", max_length=300),
        ),
    ]
