# Generated by Django 5.2.4 on 2025-10-29 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0046_alter_proformainvoice_mode_payment"),
    ]

    operations = [
        migrations.AddField(
            model_name="proformainvoice",
            name="terms_note",
            field=models.TextField(blank=True, null=True),
        ),
    ]
