# Generated by Django 5.2.4 on 2025-10-29 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0047_proformainvoice_terms_note"),
    ]

    operations = [
        migrations.AddField(
            model_name="proformainvoice",
            name="gst",
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name="proformainvoice",
            name="prpc_rate",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
