# Generated by Django 5.2.4 on 2025-10-29 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0048_proformainvoice_gst_alter_proformainvoice_prpc_rate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="proformainvoice",
            name="quantity",
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=15),
        ),
    ]
