# Generated by Django 5.2.4 on 2025-10-29 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0049_alter_proformainvoice_quantity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="proformainvoice",
            name="total",
            field=models.CharField(),
        ),
    ]
