# Generated by Django 5.2.4 on 2025-10-30 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0050_alter_proformainvoice_total"),
    ]

    operations = [
        migrations.AlterField(
            model_name="proformainvoice",
            name="prpc_rate",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="proformainvoice",
            name="quantity",
            field=models.CharField(max_length=200),
        ),
    ]
