# Generated by Django 5.2.4 on 2025-10-30 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0051_alter_proformainvoice_prpc_rate_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="proformainvoice",
            name="gst",
            field=models.CharField(max_length=200),
        ),
    ]
