# Generated by Django 5.2.4 on 2025-11-05 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0054_alter_proformainvoice_billing_state_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="proformainvoice",
            name="gst_value",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="proformainvoice",
            name="taxable_value",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
