# Generated by Django 5.2.4 on 2025-11-06 07:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0055_proformainvoice_gst_value_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="proformainvoice",
            name="cylinder_size",
        ),
        migrations.RemoveField(
            model_name="proformainvoice",
            name="gst",
        ),
        migrations.RemoveField(
            model_name="proformainvoice",
            name="gst_value",
        ),
        migrations.RemoveField(
            model_name="proformainvoice",
            name="job_name",
        ),
        migrations.RemoveField(
            model_name="proformainvoice",
            name="pouch_open_size",
        ),
        migrations.RemoveField(
            model_name="proformainvoice",
            name="prpc_rate",
        ),
        migrations.RemoveField(
            model_name="proformainvoice",
            name="quantity",
        ),
        migrations.RemoveField(
            model_name="proformainvoice",
            name="taxable_value",
        ),
        migrations.RemoveField(
            model_name="proformainvoice",
            name="title",
        ),
        migrations.RemoveField(
            model_name="proformainvoice",
            name="total",
        ),
        migrations.AlterField(
            model_name="proformainvoice",
            name="invoice_no",
            field=models.CharField(max_length=200),
        ),
        migrations.CreateModel(
            name="ProformaJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("job_name", models.CharField(max_length=200)),
                ("quantity", models.CharField(max_length=200)),
                ("pouch_open_size", models.CharField(max_length=200)),
                ("cylinder_size", models.CharField(max_length=200)),
                ("prpc_rate", models.CharField(max_length=200)),
                ("gst", models.CharField(max_length=200)),
                (
                    "taxable_value",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("gst_value", models.CharField(blank=True, max_length=200, null=True)),
                ("total", models.CharField(max_length=200)),
                (
                    "proforma_invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="job_details",
                        to="app.proformainvoice",
                    ),
                ),
            ],
        ),
    ]
