# Generated by Django 5.2.4 on 2025-11-06 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0056_remove_proformainvoice_cylinder_size_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="proformajob",
            name="gst",
        ),
        migrations.RemoveField(
            model_name="proformajob",
            name="gst_value",
        ),
        migrations.RemoveField(
            model_name="proformajob",
            name="taxable_value",
        ),
        migrations.RemoveField(
            model_name="proformajob",
            name="total",
        ),
        migrations.AddField(
            model_name="proformainvoice",
            name="gst",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="proformainvoice",
            name="gst_value",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="proformainvoice",
            name="taxable_value",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="proformainvoice",
            name="total",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
