# Generated by Django 5.2.4 on 2025-11-07 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0057_remove_proformajob_gst_remove_proformajob_gst_value_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="proformajob",
            name="taxable_value",
            field=models.IntegerField(default=0),
        ),
    ]
