# Generated by Django 5.2.4 on 2025-11-07 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0058_proformajob_taxable_value"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="proformainvoice",
            name="taxable_value",
        ),
        migrations.AddField(
            model_name="proformainvoice",
            name="total_taxable_value",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
