# Generated by Django 5.2.4 on 2025-11-07 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0059_remove_proformainvoice_taxable_value_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="proformainvoice",
            old_name="total_taxable_value",
            new_name="taxable_value",
        ),
    ]
