# Generated by Django 5.2.4 on 2025-11-07 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0060_rename_total_taxable_value_proformainvoice_taxable_value"),
    ]

    operations = [
        migrations.RenameField(
            model_name="proformainvoice",
            old_name="taxable_value",
            new_name="total_taxable_value",
        ),
    ]
