# Generated by Django 5.2.4 on 2025-11-07 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0061_rename_taxable_value_proformainvoice_total_taxable_value"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="proformajob",
            name="taxable_value",
        ),
    ]
