# Generated by Django 5.2.4 on 2025-11-10 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0062_remove_proformajob_taxable_value"),
    ]

    operations = [
        migrations.AddField(
            model_name="proformainvoice",
            name="invoice_status",
            field=models.CharField(
                blank=True,
                choices=[("Pending", "Pending"), ("Confirmed", "confirmed")],
                max_length=200,
                null=True,
            ),
        ),
    ]
