# Generated by Django 5.2.4 on 2025-11-10 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0063_proformainvoice_invoice_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="proformainvoice",
            name="invoice_status",
            field=models.CharField(
                blank=True,
                choices=[("Pending", "Pending"), ("Confirmed", "Confirmed")],
                max_length=200,
                null=True,
            ),
        ),
    ]
